language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - MIDGARD_EXT_VERSION=ratatoskr
  - MIDGARD_EXT_VERSION=master

matrix:
  allow_failures:
    - php: 5.5

before_script:
  - ./test/travis_midgard2.sh
  - sudo `which composer` self-update
  - sudo OPENPSA_INSTALLER_DBTYPE=SQLite `which composer` install

script: phpunit --debug

notifications:
    irc: "irc.freenode.org#midgard"
