language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - MIDGARD_EXT_VERSION=ratatoskr
  - MIDGARD_EXT_VERSION=master

before_script:
  - ./test/travis_midgard2.sh
  - sudo OPENPSA_INSTALLER_DBTYPE=SQLite `which composer` install

script: valgrind -v --log-file=failure.log phpunit --debug; cat failure.log

notifications:
    irc: "irc.freenode.org#midgard"
