language: php

php:
  - 5.3
  - 5.4

env:
  - MIDGARD_EXT_VERSION=ratatoskr
  - MIDGARD_EXT_VERSION=master

before_script:
  - ./test/travis_midgard2.sh
  - export OPENPSA_SKIP_DB_CREATION=true && sudo `which composer` install --verbose

script: phpunit --debug

notifications:
    irc: "irc.freenode.org#midgard"
